export const getCategorias = async (): Promise<any[]> => [];
export const getPratos = async (): Promise<any[]> => [];
export const getFichaTecnica = async (id: string) => null;
export const getMateriasPrimas = async (): Promise<any[]> => [];
export const getInsumos = async (): Promise<any[]> => [];
export const getAllPratosWithIngredientes = async (): Promise<any[]> => [];
export const saveMateriaPrima = async (data: any) => ({});
export const deleteMateriaPrima = async (id: string) => ({});
export const saveCategoria = async (data: any) => ({});
export const createCategoria = async (data: any) => ({});
export const updateCategoria = async (id: string, data: any) => ({});
export const deleteCategoria = async (id: string) => ({});
export const savePrato = async (data: any) => ({});
export const updatePrato = async (id: string, data: any, ingredientes?: any) => ({});
export const createPrato = async (data: any, ingredientes?: any) => ({});
export const deletePrato = async (id: string) => ({});
export const deletePratoWithImage = async (id: string, image?: string) => ({});
export const updateInsumo = async (id: string, data: any) => ({});
export const createInsumo = async (data: any) => ({});
export const deleteInsumo = async (id: string) => ({});
export const deletePratoImage = async (url: string) => ({});
export const uploadPratoImage = async (id: string, file: File) => ({});
